### ISSUE TITLE
Doesn't install if cython not available

### ISSUE THREAD

**Issue by alastair** [georgid/AlignmentDuration#22]
If cython is not available, this package fails `setup.py install` with this error:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/mnt/compmusic/itri/jenkins/jobs/Dunya/workspace/env/src/alignment-duration/setup.py", line 62, in <module>
        cmdclass = {'build_ext': build_ext},
    NameError: name 'build_ext' is not defined
```

This is preventing dunya from building and running tests, and so we have currently removed it as a dependency

**Comment by georgid** [comment]
the problem is that we cannot install python as dependency or that the setup.py is not correct? 

I assume the second:
Cython is necessary  dependency of https://github.com/mtg/sms-tools/ which I use. Since sms-tools itself does not have setup.py, I think we have to discuss how to make sms-tools available as external dependency. 

Two ways: 
1) use as an example the setup  from the fork https://github.com/bzamecnik/sms-tools/blob/master/setup.py
2) sms-tools is copied as a python package of alignment-duration. So I have copied in https://github.com/georgid/AlignmentDuration/blob/IntegratedPycompMusic/setup.py the contents of https://github.com/MTG/sms-tools/blob/master/software/models/utilFunctions_C/compileModule.py

I did the second way but don't quite understand if I did it right as I am not competent with cython. Anybody familiar with how to put the contents of https://github.com/MTG/sms-tools/blob/master/software/models/utilFunctions_C/compileModule.py in setup.py?
maybe @sankalpg can give an idea?

**Comment by andrebola** [comment]
@georgi, we were looking this issue. 
I think with changing the setup.py is enough to fix this issue. If you have any question about how to do that I can help you, I think you should only remove the try/except and leave cython as a dependency.

**Comment by georgid** [comment]
Now cython is required, may you test and close if installs fine.
